apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: pv-blob-config
    volumeAttributes:
      resourceGroup: ${RESOURCE_GROUP}
      containerName: ${CONTAINER_NAME}
      storageAccount: ${STORAGE_ACCOUNT}
    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-blob-config
  storageClassName: azureblob-fuse-premium