apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: azurefile-premium
  csi:
    driver: file.csi.azure.com
    volumeHandle: ${STORAGE_ACCOUNT}_${SHARE_NAME}
    volumeAttributes:
      resourceGroup: ${RESOURCE_GROUP}
      shareName: ${SHARE_NAME}
      storageAccount: ${STORAGE_ACCOUNT}
    nodeStageSecretRef:
      name: azure-file-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-azurefile-config
  storageClassName: azurefile-premium