apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker  
  labels:
    app: locust-worker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      nodeSelector:
        app: locust-worker
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: pvc-azurefile-config
      containers:
      - name: locust-worker
        image: ${IMAGE_NAME}
        imagePullPolicy: Always
        env:
          - name: LOCUST_OPTIONS
            value: "--worker --master-host master"
        ports:
        - containerPort: 8089
        volumeMounts:
        - name: config-volume
          mountPath: /app/config