type: CosmosDB
tasks:
  - taskName: insert1
    taskWeight: 25
    command:
      type: insert
      database: lab
      container: cart
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
          as: string
        - name: "@ticket_id"
          type: guid
          as: string
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant
          value: "[1,2,3,4,5,6]"
          as: string
      document:
        player_id: "@player_id"
        id: "@ticket_id"
        ticket_date: "@ticket_date"
        contest: "@contest"
        numbers: "@numbers"
        metadata:
          createdBy: "benchmark"
          tags:
            - "test"
            - "cosmos"
          nested:
            info: "example"
            value: 123

  - taskName: upsert1
    taskWeight: 25
    command:
      type: upsert
      database: lab
      container: cart
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
          as: string
        - name: "@ticket_id"
          type: guid
          as: string
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant
          value: "[1,2,3,4,5,6]"
          as: string
      document:
        player_id: "@player_id"
        id: "@ticket_id"
        ticket_date: "@ticket_date"
        contest: "@contest"
        numbers: "@numbers"
        extra:
          details:
            source: "upsert"
            timestamp: "@ticket_date"

  - taskName: delete1
    taskWeight: 15
    command:
      type: delete
      database: lab
      container: cart
      partitionKey:
        - "@player_id"
      id: "@ticket_id"
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
          as: string
        - name: "@ticket_id"
          type: guid
          as: string

  - taskName: point_read1
    taskWeight: 15
    command:
      type: point_read
      database: lab
      container: cart
      partitionKey:
        - "@player_id"
      id: "@ticket_id"
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
          as: string
        - name: "@ticket_id"
          type: guid
          as: string

  - taskName: select1
    taskWeight: 20
    command:
      type: select
      database: lab
      container: cart
      query: 'SELECT * FROM cart c WHERE c.player_id = @player_id'
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
          as: string