type: MongoDB
tasks:
  - taskName: insert1
    taskWeightPct: 50
    command:
      type: insert
      database: lab
      collection: cart
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
        - name: "@ticket_id"
          type: guid
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant_string
          value: "[1,2,3,4,5,6]"
      document:
        player_id: "@player_id"
        ticket_id: "@ticket_id"
        ticket_date: "@ticket_date"
        contest: "@contest"
        numbers: "@numbers"
  - taskName: insert1
    taskWeightPct: 50
    command:
      type: insert
      database: lab
      collection: teste1
      parameters:
        - name: "@c1"
          type: random_int
          start: 1
          end: 150000000
        - name: "@c2"
          type: faker.fullname
      document:
        c1: "@c1"
        c2: "@c2"
        c3: "$$NOW"