type: SQL
runStartUpFrequency: Never
tasks:
  - taskName: insert
    taskWeight: 5
    command:
      type: prepared
      definition: INSERT INTO cart (player_id, ticket_id, ticket_date, contest, numbers) VALUES (@player_id, @ticket_id, @ticket_date, @contest, @numbers)
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
        - name: "@ticket_id"
          type: guid
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant
          value: "[1,2,3,4,5,6]"
          as: string

  - taskName: update
    taskWeight: 0
    command:
      definition: UPDATE cart SET numbers = @numbers WHERE player_id = @player_id
      parameters:
        - name: "@numbers"
          type: constant
          value: "[7,8,9,10,11,12]"
          as: string
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000

  - taskName: delete
    taskWeight: 0
    command:
      definition: DELETE FROM cart WHERE player_id = @player_id
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000

  - taskName: select
    taskWeight: 15
    command:
      type: ad-hoc
      definition: SELECT * FROM cart WHERE player_id = @player_id
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000

  - taskName: stored_procedure
    taskWeight: 80
    command:
      type: stored_procedure
      definition: sp_cart_ins
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
        - name: "@ticket_id"
          type: guid
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant
          value: "[1,2,3,4,5,6]"
          as: string

  - taskName: bulk_insert
    taskWeight: 0
    command:
      type: bulk_insert
      tableName: cart
      batchSize: 1000
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
        - name: "@ticket_id"
          type: guid
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant
          value: "[1,2,3,4,5,6]"
          as: string