type: SQL
tasks:
  - taskName: insert1
    taskWeightPct: 50
    command:
      definition: INSERT INTO cart (player_id, ticket_id, ticket_date, contest, numbers) VALUES (@player_id, @ticket_id, @ticket_date, @contest, @numbers)
      parameters:
        - name: "@player_id"
          type: random_int
          start: 1
          end: 150000000
        - name: "@ticket_id"
          type: guid
        - name: "@ticket_date"
          type: datetime
        - name: "@contest"
          type: random_int
          start: 1
          end: 1000
        - name: "@numbers"
          type: constant_string
          value: "[1,2,3,4,5,6]"
  - taskName: insert2
    taskWeightPct: 50
    command:
      definition: INSERT INTO teste1 (c1, c2, c3) VALUES (@c1, @c2, getdate())
      parameters:
        - name: "@c1"
          type: random_int
          start: 1
          end: 150000000
        - name: "@c2"
          type: faker.fullname